# Generated by Django 3.2.7 on 2021-10-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('mac', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='Computer', max_length=18)),
                ('port', models.IntegerField()),
                ('ip', models.GenericIPAddressField()),
                ('last_seen', models.DateTimeField()),
                ('is_alive', models.BooleanField(default=True)),
            ],
        ),
    ]
