# Generated by Django 3.2.7 on 2021-10-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khS4_pc_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='name',
            field=models.CharField(default='Computer', max_length=18),
        ),
    ]
