# Generated by Django 3.2.7 on 2021-10-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khS4_pc_master', '0002_computer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
    ]
