# Generated by Django 3.2.7 on 2021-10-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khS4_pc_master', '0003_computer_is_alive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
